spring:
  application:
     name: zuul

server:
   port: 3001

eureka:
  client:
    service-url:
       defaultZone: http://eureka1:2001/eureka,http://eureka:2002/eureka  
       
zuul:
  routes:
    mydept.serviceId: item-service  
    mydept.path: /item/**         
